### ISSUE TITLE
redirect loop

### ISSUE THREAD

**Issue by maulanahusains** [Quegeon/Projectan101-Pencatatan-Pelanggaran#20]
mas, saya gada data aturan. mau bikin, tapi baru ngeuh di controller kalau data aturan kosong bakal ngeredirect ulang. gimana kalau dihapus aja mas si aturan->first di if nya
![image](https://github.com/Quegeon/Projectan101-Pencatatan-Pelanggaran/assets/126932455/d30820e5-cae6-4524-a3cf-45276d411280)

nah ini menurut saya masalahnya
![image](https://github.com/Quegeon/Projectan101-Pencatatan-Pelanggaran/assets/126932455/b1747f12-2922-4931-b166-4907e234fd9f)

atau emng bikin pake seeder aja? saya ngikut sih, tadi pin masukin data ngasal doang buat ngecek di pelanggaran

**Comment by Quegeon** [comment]
sori baru baca, iya itu seharusnya gk ngevalidate $aturan. aku coba ganti
