### ISSUE TITLE
Add Timeout On Validate Error Handling

### ISSUE THREAD

**Issue by Quegeon** [Quegeon/Projectan101-Pencatatan-Pelanggaran#50]
Menambahkan _Timeout_ pada _Error_ _Messages_ dari fungsi _Validate_ di _Form_

ex. Tambahkan `timeout` pada `<p class ="text-danger">` sehingga menjadi `<p class ="text-danger timeout">`

**Comment by maulanahusains** [comment]
Laksanakan🫡

**Comment by Quegeon** [comment]
Sepertinya sama saya saja, sekalian memnyesuaikan kodingan

**Comment by maulanahusains** [comment]
> Sepertinya sama saya saja, sekalian memnyesuaikan kodingan

okeh kak, semangat
